#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: Build OpenWrt(lean)[schedule]

on:
  #repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  schedule:
    - cron: 0 3 */7 * *

env:
  REPO_URL: https://github.com/jkingben/lede.git
  REPO_BRANCH: master
  CONFIG_FILE: cfgs/x86_config_lean
  KEY_BUILD: data/opkg/key-build.pub
  DIST_FEEDS: data/opkg/distfeeds.conf
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  FEED_DIY_SH: feed_diy.sh
  FEED_UPDATE_SH: feeds_lean.sh
  TOOLCHAIN_TAG: toolchain
  UPLOAD_TOOLCHAIN: true
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  FREE_UP_DISK: true
  COMBINE_DISK: true
  TZ: Asia/Shanghai

jobs:
  Toolchain:
    runs-on: ubuntu-20.04

