#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: Sync task for lienol[schedule]

on:
  #repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  schedule:
    - cron: 0 0 */3 * *

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        date=$(date +%Y%m%d%H%M%S)
        echo "DATE=$date" >> $GITHUB_ENV

    - name: Sync my packages
      run: |
        mkdir mypkg
        git clone https://github.com/Lienol/openwrt-packages.git -b 22.03 mypkg/pkg
        git clone https://github.com/Lienol/openwrt-luci.git -b 22.03 mypkg/luci
        git clone https://github.com/kenzok8/openwrt-packages.git kenzok8
        rm -rf mypkg/pkg/.git*
        rm -rf mypkg/luci/.git*
        rm -rf mypkg/pkg/net/smartdns
        rm -rf mypkg/luci/applications/luci-app-smartdns
        cp -r kenzok8/smartdns mypkg/pkg/net
        cp -r kenzok8/mosdns mypkg/pkg/net
        cp -r kenzok8/luci-app-smartdns mypkg/luci/applications
        cp -r kenzok8/luci-app-mosdns mypkg/luci/applications
        cp -r kenzok8/luci-theme-atmaterial_new mypkg/luci/themes
        cp -r kenzok8/luci-theme-neobird mypkg/luci/themes
        echo -e '\nmsgid "Local DNS Lists"' >> mypkg/luci/applications/luci-app-mosdns/po/zh-cn/mosdns.po
        echo 'msgstr "国内解析"' >> mypkg/luci/applications/luci-app-mosdns/po/zh-cn/mosdns.po
        echo -e '\nmsgid "Forced to use domestic dns resolution"' >> mypkg/luci/applications/luci-app-mosdns/po/zh-cn/mosdns.po
        echo 'msgstr "强制用国内dns解析"' >> mypkg/luci/applications/luci-app-mosdns/po/zh-cn/mosdns.po
        sed -i '/white_list_file/ilocal localdns_list_file = "/etc/mosdns/rule/localdns.txt"' mypkg/luci/applications/luci-app-mosdns/luasrc/model/cbi/mosdns/rule_list.lua
        sed -i -e '/s\:tab/{is:tab("localdns_list", translate("Local DNS Lists"))' -e ':a;n;ba}' mypkg/luci/applications/luci-app-mosdns/luasrc/model/cbi/mosdns/rule_list.lua
        sed -i -e '/s\:taboption/{io = s:taboption("localdns_list", TextValue, "localdnslist", "", "<font color='red'>" .. translate("Forced to use domestic dns resolution") .. "</font>")\no.rows = 15\no.wrap = "off"\no.cfgvalue = function(self, section) return nixio.fs.readfile(localdns_list_file) or "" end\no.write = function(self, section, value) nixio.fs.writefile(localdns_list_file, value:gsub("\\r\\n", "\\n")) end\no.remove = function(self, section, value) nixio.fs.writefile(localdns_list_file, "") end\no.validate = function(self, value)\n    return value\nend\n' -e ':a;n;ba}' mypkg/luci/applications/luci-app-mosdns/luasrc/model/cbi/mosdns/rule_list.lua
        touch mypkg/luci/applications/luci-app-mosdns/root/etc/mosdns/rule/localdns.txt
        cp -f cfgs/mosdns_cus_config.yaml mypkg/luci/applications/luci-app-mosdns/root/etc/mosdns/cus_config.yaml

    - name: Push my packages
      uses: s0/git-publish-subdir-action@develop
      env:
          REPO: self
          BRANCH: packages_lienol
          FOLDER: mypkg/pkg
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ${{ env.DATE }}({sha})"
    - name: Push my luci
      uses: s0/git-publish-subdir-action@develop
      env:
          REPO: self
          BRANCH: luci_lienol
          FOLDER: mypkg/luci
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ${{ env.DATE }}({sha})"

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3
