#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: Test SSH

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set Date
      run: |
        sudo timedatectl set-timezone 'Asia/Shanghai'
        date=$(date +%Y%m%d)
        echo "DATE=$date" >> $GITHUB_ENV
        
    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        
    - name: Upload-Files-Action
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        username: 'root'
        server: '${{ secrets.SFTP_SERVER_IP }}'
        port: 2222
        ssh_private_key: ${{ secrets.SFTP_PRIVATE_KEY }}
        local_path: './*'
        remote_path: '/www/openwrt/snapshots'
