#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: Test SSH

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set Date
      run: |
        sudo timedatectl set-timezone 'Asia/Shanghai'
        date=$(date +%Y%m%d)
        echo "DATE=$date" >> $GITHUB_ENV
        
    - name: Upload bin directory
      uses: actions/upload-artifact@main
      with:
        name: OpenWrt_bin123
        path: ./

    #- name: SSH connection to Actions
     # uses: P3TERX/ssh2actions@v1.0.0
      #env:
        #TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        #TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        
    #- name: Upload-Files-Action
    #  run: |
    #    echo 'put -r ./* /www/openwrt/snapshots' > upload
    #    echo '${{ secrets.SFTP_PRIVATE_KEY }}' > ssh_key
    #    chmod 600 ssh_key
    #    ssh -o StrictHostKeyChecking=no -p 2222 -i ssh_key root@${{ secrets.SFTP_SERVER_IP }} mkdir -p /www/openwrt/snapshots
    #    sftp -o StrictHostKeyChecking=no -b upload -P 2222 -i ssh_key root@${{ secrets.SFTP_SERVER_IP }}
    #    echo 'upload finished'
