#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: Test SSH

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  REPO_URL: https://github.com/Lienol/openwrt
  REPO_BRANCH: 22.03
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set Date
      run: |
        sudo timedatectl set-timezone "$TZ"
        date=$(date +%Y%m%d%H%M%S)
        echo "DATE=$date" >> $GITHUB_ENV
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Generate release tag
      id: tag
      run: |
        echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M[REPO_$REPO_BRANCH]")"

    - name: Print release tag
      run: |
        echo ${{ steps.tag.outputs.release_tag }}

    - name: Clone source code
      run: |
        mkdir mypkg
        git clone https://github.com/Lienol/openwrt-packages.git -b 22.03 mypkg/pkg
        git clone https://github.com/Lienol/openwrt-luci.git -b 22.03 mypkg/luci
        git clone https://github.com/kenzok8/openwrt-packages.git kenzok8
        rm -rf mypkg/pkg/.git*
        rm -rf mypkg/luci/.git*
        rm -rf mypkg/pkg/net/smartdns
        rm -rf mypkg/luci/applications/luci-app-smartdns
        cp -r kenzok8/smartdns mypkg/pkg/net
        cp -r kenzok8/mosdns mypkg/pkg/net
        cp -r kenzok8/luci-app-smartdns mypkg/luci/applications
        cp -r kenzok8/luci-app-mosdns mypkg/luci/applications
        cp -r kenzok8/luci-theme-atmaterial_new mypkg/luci/themes
        cp -r kenzok8/luci-theme-neobird mypkg/luci/themes

    - name: Push openwrt
      uses: s0/git-publish-subdir-action@develop
      env:
          REPO: self
          BRANCH: others
          FOLDER: mypkg
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ${{ env.DATE }}({sha})"

#     - name: Clone source code
#       run: |
#         df -hT $PWD
#         git clone $REPO_URL -b $REPO_BRANCH openwrt
#         ln -sf $GITHUB_WORKSPACE/openwrt /workdir/openwrt
#     - name: Cache
#       uses: klever1988/cachewrtbuild@main
#       with:
#         ccache: 'true'
#         prefix: ${{ github.workspace }}/openwrt
        
#     - name: Push openwrt
#       uses: s0/git-publish-subdir-action@develop
#       env:
#           REPO: self
#           BRANCH: build
#           FOLDER: openwrt/include
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           MESSAGE: "Build: ({sha}) {msg}"

#     - name: Update version
#       run: mkdir _ver && echo "${{ env.DATE }}" > _ver/version
    
#     - name: Push self      
#       uses: s0/git-publish-subdir-action@develop
#       env:
#           REPO: self
#           BRANCH: main
#           FOLDER: _ver
#           CLEAR_GLOBS_FILE: ".clear-target-files"
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           MESSAGE: "Build: ({sha}) {msg}"

    #- name: SSH connection to Actions
     # uses: P3TERX/ssh2actions@v1.0.0
      #env:
        #TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        #TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        
    #- name: Upload-Files-Action
    #  run: |
    #    echo 'put -r ./* /www/openwrt/snapshots' > upload
    #    echo '${{ secrets.SFTP_PRIVATE_KEY }}' > ssh_key
    #    chmod 600 ssh_key
    #    ssh -o StrictHostKeyChecking=no -p 2222 -i ssh_key root@${{ secrets.SFTP_SERVER_IP }} mkdir -p /www/openwrt/snapshots
    #    sftp -o StrictHostKeyChecking=no -b upload -P 2222 -i ssh_key root@${{ secrets.SFTP_SERVER_IP }}
    #    echo 'upload finished'
